<a href="https://colab.research.google.com/github/XuRui314/MIT_6.036_homework_zxr/blob/main/MIT6_036_hw06_Neural_Network_colab_notebook_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MIT 6.036 Spring 2019: Homework 6

This homework does not include provided Python code. Instead, we encourage you to write your own code to help you answer some of these problems, and/or test and debug the code components we do ask for. All of the problems should be simple enough that hand calculation should be possible, but it may be convenient to write some short programs to explore the neural networks, particularly for problem 2.


In [ ]:
import numpy as np

def SM(z):
  # implement softmax
  ez = np.exp(z)
  return ez / np.sum(ez, axis = 0)


 **Problem 2A**

In [ ]:
z = np.array([[-1, 0, 1]]).T
# your code here

**Problem 2.C-F**

In [ ]:
w = np.array([[1, -1, -2], [-1, 2, 1]])
x = np.array([[1], [1]])
y = np.array([[0, 1, 0]]).T
# your code here
z = w.T@x
a = SM(z)
df = x @ (a-y).T
print(df)

[[ 0.24472847 -0.33475904  0.09003057]
 [ 0.24472847 -0.33475904  0.09003057]]


**Problem 3**

In [ ]:
# layer 1 weights
w_1 = np.array([[1, 0, -1, 0], [0, 1, 0, -1]])
w_1_bias = np.array([[-1, -1, -1, -1]]).T
# layer 2 weights
w_2 = np.array([[1, -1], [1, -1], [1, -1], [1, -1]])
w_2_bias = np.array([[0, 2]]).T

# your code here

In [ ]:
import numpy as np

T  = np.matrix([[0.0 , 0.1 , 0.9 , 0.0],
[0.9 , 0.1 , 0.0 , 0.0],
[0.0 , 0.0 , 0.1 , 0.9],
[0.9 , 0.0 , 0.0 , 0.1]])
g = 0.9
r = np.matrix([0, 1., 0., 2.]).reshape(4, 1)

print(np.linalg.solve(np.eye(4) - g * T, r))

[[6.05288295]
 [6.48663207]
 [6.7519581 ]
 [7.58553317]]
