<a href="https://colab.research.google.com/github/XuRui314/MIT_6.036_homework_zxr/blob/main/MIT_6_036_HW06_Neural_Network_colab_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MIT 6.036 Spring 2019: Homework 6

This homework does not include provided Python code. Instead, we encourage you to write your own code to help you answer some of these problems, and/or test and debug the code components we do ask for. All of the problems should be simple enough that hand calculation should be possible, but it may be convenient to write some short programs to explore the neural networks, particularly for problem 2.


In [26]:
import numpy as np

def SM(z):
  # implement softmax
  return np.exp(z) / np.sum(np.exp(z), axis = 0)


 **Problem 2A**

In [27]:
z = np.array([[-1, 0, 1]]).T
SM(z).tolist()

[[0.09003057317038046], [0.24472847105479767], [0.6652409557748219]]

**Problem 2.C-F**

Use the formula ${\partial  \over \partial W^L_{k,j}}NLL(a^L,y) = x_k(a^L_j - y_j)$

The matrix form is ${\partial  \over \partial W^L}NLL(a^L,y) = x(a^L - y)^T$

In [28]:
w = np.array([[1, -1, -2], [-1, 2, 1]])
x = np.array([[1], [1]])
y = np.array([[0, 1, 0]]).T

# linear sum
z = w.T@x
# activation function
a = SM(z)

dw = x @ (a-y).T
print(df)

[[ 0.24472847 -0.33475904  0.09003057]
 [ 0.24472847 -0.33475904  0.09003057]]


In [29]:
# probability
SM(w.T@x)

array([[0.24472847],
       [0.66524096],
       [0.09003057]])

In [30]:
# update
step_size = 0.5
w1 =w - dw * step_size
w1

array([[ 0.87763576, -0.83262048, -2.04501529],
       [-1.12236424,  2.16737952,  0.95498471]])

In [31]:
# probability
SM(w1.T@x)

array([[0.15918761],
       [0.77245284],
       [0.06835955]])

**Problem 3**

In [32]:
# layer 1 weights
w_1 = np.array([[1, 0, -1, 0], [0, 1, 0, -1]])
w_1_bias = np.array([[-1, -1, -1, -1]]).T
# layer 2 weights
w_2 = np.array([[1, -1], [1, -1], [1, -1], [1, -1]])
w_2_bias = np.array([[0, 2]]).T

x = np.array([[3, 14]]).T
z_1 = w_1.T@x + w_1_bias
a_1 = np.where( z_1 > 0,z_1, 0)

z_2 = w_2.T@a_1 + w_2_bias
a_2 = SM(z_2)
a_2


array([[1.00000000e+00],
       [6.91440011e-13]])

In [38]:
x1 = np.array([[0, 2]]).T
z = w_1.T@x1 + w_1_bias
a = np.where( z > 0,z, 0)
a

array([[0],
       [1],
       [0],
       [0]])

In [20]:
import numpy as np

T  = np.matrix([[0.0 , 0.1 , 0.9 , 0.0],
[0.9 , 0.1 , 0.0 , 0.0],
[0.0 , 0.0 , 0.1 , 0.9],
[0.9 , 0.0 , 0.0 , 0.1]])
g = 0.9
r = np.matrix([0, 1., 0., 2.]).reshape(4, 1)

print(np.linalg.solve(np.eye(4) - g * T, r))

[[6.05288295]
 [6.48663207]
 [6.7519581 ]
 [7.58553317]]
